In [2]:
import pandas as pnd
from datetime import date
import numpy as np
import operator

In [4]:
data=pnd.read_csv('rideshare_kaggle.csv')
pnd.set_option('display.max_columns',None)
data.head()

,id,timestamp,hour,day,month,datetime,timezone,source,destination,cab_type,product_id,name,price,distance,surge_multiplier,latitude,longitude,temperature,apparentTemperature,short_summary,long_summary,precipIntensity,precipProbability,humidity,windSpeed,windGust,windGustTime,visibility,temperatureHigh,temperatureHighTime,temperatureLow,temperatureLowTime,apparentTemperatureHigh,apparentTemperatureHighTime,apparentTemperatureLow,apparentTemperatureLowTime,icon,dewPoint,pressure,windBearing,cloudCover,uvIndex,visibility.1,ozone,sunriseTime,sunsetTime,moonPhase,precipIntensityMax,uvIndexTime,temperatureMin,temperatureMinTime,temperatureMax,temperatureMaxTime,apparentTemperatureMin,apparentTemperatureMinTime,apparentTemperatureMax,apparentTemperatureMaxTime
0,424553bb-7174-41ea-aeb4-fe06d4f4b9d7,1.544953e+09,9,16,12,2018-12-16 09:30:07,America/New_York,Haymarket Square,North Station,Lyft,lyft_line,Shared,5.0,0.44,1.0,42.2148,-71.033,42.34,37.12,Mostly Cloudy,Rain throughout the day.,0.0000,0.0,0.68,8.66,9.17,1545015600,10.000,43.68,1544968800,34.19,1545048000,37.95,1544968800,27.39,1545044400,partly-cloudy-night,32.70,1021.98,57,0.72,0,10.000,303.8,1544962084,1544994864,0.30,0.1276,1544979600,39.89,1545012000,43.68,1544968800,33.73,1545012000,38.07,1544958000
1,4bd23055-6827-41c6-b23b-3c491f24e74d,1.543284e+09,2,27,11,2018-11-27 02:00:23,America/New_York,Haymarket Square,North Station,Lyft,lyft_premier,Lux,11.0,0.44,1.0,42.2148,-71.033,43.58,37.35,Rain,"Rain until morning, starting again in the eve...",0.1299,1.0,0.94,11.98,11.98,1543291200,4.786,47.30,1543251600,42.10,1543298400,43.92,1543251600,36.20,1543291200,rain,41.83,1003.97,90,1.00,0,4.786,291.1,1543232969,1543266992,0.64,0.1300,1543251600,40.49,1543233600,47.30,1543251600,36.20,1543291200,43.92,1543251600
2,981a3613-77af-4620-a42a-0c0866077d1e,1.543367e+09,1,28,11,2018-11-28 01:00:22,America/New_York,Haymarket Square,North Station,Lyft,lyft,Lyft,7.0,0.44,1.0,42.2148,-71.033,38.33,32.93,Clear,Light rain in the morning.,0.0000,0.0,0.75,7.33,7.33,1543334400,10.000,47.55,1543320000,33.10,1543402800,44.12,1543320000,29.11,1543392000,clear-night,31.10,992.28,240,0.03,0,10.000,315.7,1543319437,1543353364,0.68,0.1064,1543338000,35.36,1543377600,47.55,1543320000,31.04,1543377600,44.12,1543320000
3,c2d88af2-d278-4bfd-a8d0-29ca77cc5512,1.543554e+09,4,30,11,2018-11-30 04:53:02,America/New_York,Haymarket Square,North Station,Lyft,lyft_luxsuv,Lux Black XL,26.0,0.44,1.0,42.2148,-71.033,34.38,29.63,Clear,Partly cloudy throughout the day.,0.0000,0.0,0.73,5.28,5.28,1543514400,10.000,45.03,1543510800,28.90,1543579200,38.53,1543510800,26.20,1543575600,clear-night,26.64,1013.73,310,0.00,0,10.000,291.1,1543492370,1543526114,0.75,0.0000,1543507200,34.67,1543550400,45.03,1543510800,30.30,1543550400,38.53,1543510800
4,e0126e1f-8ca9-4f2e-82b3-50505a09db9a,1.543463e+09,3,29,11,2018-11-29 03:49:20,America/New_York,Haymarket Square,North Station,Lyft,lyft_plus,Lyft XL,9.0,0.44,1.0,42.2148,-71.033,37.44,30.88,Partly Cloudy,Mostly cloudy throughout the day.,0.0000,0.0,0.70,9.14,9.14,1543446000,10.000,42.18,1543420800,36.71,1543478400,35.75,1543420800,30.29,1543460400,partly-cloudy-night,28.61,998.36,303,0.44,0,10.000,347.7,1543405904,1543439738,0.72,0.0001,1543420800,33.10,1543402800,42.18,1543420800,29.11,1543392000,35.75,1543420800

In [28]:
data=data.sort_values('datetime')
data=data[['id','timestamp','hour','day','month','datetime','source','destination','cab_type','product_id','name','price','distance','surge_multiplier','temperature','short_summary','long_summary','icon','visibility','temperatureHigh','temperatureLow','apparentTemperatureHigh','apparentTemperatureLow','latitude','longitude']]
data.head()

,id,timestamp,hour,day,month,datetime,source,destination,cab_type,product_id,name,price,distance,surge_multiplier,temperature,short_summary,long_summary,icon,visibility,temperatureHigh,temperatureLow,apparentTemperatureHigh,apparentTemperatureLow,latitude,longitude
66422,a7b50600-c6c5-4e6c-bea9-4487344196d4,1.543204e+09,3,26,11,2018-11-26 03:40:46,North Station,Haymarket Square,Uber,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX,7.0,0.56,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003
446073,9962f244-8fce-4ae9-a583-139d5d7522e1,1.543204e+09,3,26,11,2018-11-26 03:40:46,Theatre District,North End,Uber,8cf7e821-f0d3-49c6-8eba-e679c0ebcf6a,Taxi,NaN,1.57,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003
184332,4aa68a5d-abc0-4fdf-a47f-0003617afbae,1.543204e+09,3,26,11,2018-11-26 03:40:46,North End,West End,Lyft,lyft,Lyft,7.0,1.23,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003
167114,ef8b695c-c24d-4ac1-b3fe-4aa1a7ed79f4,1.543204e+09,3,26,11,2018-11-26 03:40:46,Boston University,Beacon Hill,Lyft,lyft_premier,Lux,19.5,2.66,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003
184333,89f35ef7-7129-483d-b3e6-d89afdf6946d,1.543204e+09,3,26,11,2018-11-26 03:40:46,North End,West End,Lyft,lyft_line,Shared,5.0,1.23,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 693071 entries, 66422 to 166551
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       693071 non-null  object
 1   timestamp                693071 non-null  float64
 2   hour                     693071 non-null  int64
 3   day                      693071 non-null  int64
 4   month                    693071 non-null  int64
 5   datetime                 693071 non-null  object
 6   source                   693071 non-null  object
 7   destination              693071 non-null  object
 8   cab_type                 693071 non-null  object
 9   product_id               693071 non-null  object
 10  name                     693071 non-null  object
 11  price                    637976 non-null  float64
 12  distance                 693071 non-null  float64
 13  surge_multiplier         693071 non-null  float64
 14  temperature              693071 non-null  float64
 15  short_summary            693071 non-null  object
 16  long_summary             693071 non-null  object
 17  icon                     693071 non-null  object
 18  visibility               693071 non-null  float64
 19  temperatureHigh          693071 non-null  float64
 20  temperatureLow           693071 non-null  float64
 21  apparentTemperatureHigh  693071 non-null  float64
 22  apparentTemperatureLow   693071 non-null  float64
 23  latitude                 693071 non-null  float64
 24  longitude                693071 non-null  float64
dtypes: float64(12), int64(3), object(10)
memory usage: 137.5+ MB

In [30]:
data.isna().any()

id                         False
timestamp                  False
hour                       False
day                        False
month                      False
datetime                   False
source                     False
destination                False
cab_type                   False
product_id                 False
name                       False
price                       True
distance                   False
surge_multiplier           False
temperature                False
short_summary              False
long_summary               False
icon                       False
visibility                 False
temperatureHigh            False
temperatureLow             False
apparentTemperatureHigh    False
apparentTemperatureLow     False
latitude                   False
longitude                  False
dtype: bool

In [31]:
data.isnull().sum()

id                             0
timestamp                      0
hour                           0
day                            0
month                          0
datetime                       0
source                         0
destination                    0
cab_type                       0
product_id                     0
name                           0
price                      55095
distance                       0
surge_multiplier               0
temperature                    0
short_summary                  0
long_summary                   0
icon                           0
visibility                     0
temperatureHigh                0
temperatureLow                 0
apparentTemperatureHigh        0
apparentTemperatureLow         0
latitude                       0
longitude                      0
dtype: int64

In [32]:
data['price']=data['price'].fillna(data['distance']*1.45)

In [33]:
data['source'].value_counts()

Financial District         58857
Theatre District           57813
Back Bay                   57792
Boston University          57764
North End                  57763
Fenway                     57757
Northeastern University    57756
South Station              57750
Haymarket Square           57736
West End                   57562
Beacon Hill                57403
North Station              57118
Name: source, dtype: int64

In [34]:
data['destination'].value_counts()

Financial District         58851
Theatre District           57798
Back Bay                   57780
Haymarket Square           57764
Boston University          57764
Fenway                     57757
North End                  57756
Northeastern University    57755
South Station              57749
West End                   57575
Beacon Hill                57403
North Station              57119
Name: destination, dtype: int64

In [35]:
data["datetime"] = pnd.to_datetime(data["datetime"])
type(data["datetime"])

pandas.core.series.Series

In [36]:
data['days name']=data['datetime'].dt.day_name()

In [39]:
data['time of drive'] = np.where(operator.and_(data['hour'] >= 5,data['hour']<12), 'Moring', (np.where(operator.and_(data['hour'] >= 12,data['hour']<17), 'Noon', (np.where(operator.and_(data['hour'] >= 17,data['hour']<22), 'Evening','Night')))))

In [40]:
data.to_csv('uber vs lyft.csv')
data.head()

,id,timestamp,hour,day,month,datetime,source,destination,cab_type,product_id,name,price,distance,surge_multiplier,temperature,short_summary,long_summary,icon,visibility,temperatureHigh,temperatureLow,apparentTemperatureHigh,apparentTemperatureLow,latitude,longitude,days name,time of drive
66422,a7b50600-c6c5-4e6c-bea9-4487344196d4,1.543204e+09,3,26,11,2018-11-26 03:40:46,North Station,Haymarket Square,Uber,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX,7.0000,0.56,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003,Monday,Night
446073,9962f244-8fce-4ae9-a583-139d5d7522e1,1.543204e+09,3,26,11,2018-11-26 03:40:46,Theatre District,North End,Uber,8cf7e821-f0d3-49c6-8eba-e679c0ebcf6a,Taxi,2.2765,1.57,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003,Monday,Night
184332,4aa68a5d-abc0-4fdf-a47f-0003617afbae,1.543204e+09,3,26,11,2018-11-26 03:40:46,North End,West End,Lyft,lyft,Lyft,7.0000,1.23,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003,Monday,Night
167114,ef8b695c-c24d-4ac1-b3fe-4aa1a7ed79f4,1.543204e+09,3,26,11,2018-11-26 03:40:46,Boston University,Beacon Hill,Lyft,lyft_premier,Lux,19.5000,2.66,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003,Monday,Night
184333,89f35ef7-7129-483d-b3e6-d89afdf6946d,1.543204e+09,3,26,11,2018-11-26 03:40:46,North End,West End,Lyft,lyft_line,Shared,5.0000,1.23,1.0,41.83,Foggy,Rain in the morning and afternoon.,fog,1.685,46.15,40.15,43.17,39.21,42.3429,-71.1003,Monday,Night